{% set version = "1.15.0" %}

package:
  name: cov-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cov-core/cov-core-{{ version }}.tar.gz
  sha256: 4a14c67d520fda9d42b0da6134638578caae1d374b9bb462d8de00587dba764c

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
  run:
    - python
    - coverage >=3.6

test:
  imports:
    - cov_core_init

about:
  home: https://github.com/schlamar/cov-core
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  summary: 'plugin core for use by pytest-cov, nose-cov and nose2-cov'

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
