travis:
  secure:
    BINSTAR_TOKEN: BgqBzi/d2B37A5JivYoDyrZKW847ttK2TnYb0dwldmfzFv+nDEtjrDKVcsMjQ9r5Yuo90fBbRFukQMKmtPX4ygF41VE0twoDkbS0sY8Y4Ct2la+UaC+zQJTtBprDa0oL7Mue6jgvjDBq0oABSSKAHdf+Y0JsOl1h0j6t06YnRy3NIQdWHdojPCvPGGduXZnXStRNQgW4R9oPX3zlIGOjHwUq93UGSxiWNAfoaLGQS9V5K9HarZtmtIWzehAr6j16/Z1kKSU/JynQ0Tn079a0B4Z16GAKapoqq6EJOqeHOiN3O4L6IO13jGD0nEmY+njZR3UKe4nNVJtqgBsKMOMng9MVVYqSYVsR+1qkwHNY+jbv5sCfWvUJlrz04nCtNdibcB2pJmvwnq8EiXxfiVzKFzy7096NgWCNYCAF5nSlLPxG8aAzYXLXYzrgZLsI5rMJCX2fzhx0GAFFSipqtkXkcCqG7J7ogvcFclRimUmgAJJbZes786NF/NKpeYFrn5rSvHbwGawz7eZKrPxA1fTO31ERXs1/TnmKZAcbvsZ4QTDg3Cz7G4RF3oSvxeznUtJ5sNdlnZ/lFsMQ0F9VEXyIDuq1FCj21WvsxFsQJrUAyqySXloVJzJVqhbJrkikuXh78aCswm6pnpLiNjxO+Icl6JKYXzfEkyN/JVFRqyx5nDE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
