travis:
  secure:
    BINSTAR_TOKEN: qEqnHobH2/q9d89+bo1c6P3DptEDH6DGxg4dK55xiXYhczMvaDQocC0EFYurTwrdZFUarmA/s+iO5lPd5tDzhG9DrR9UD6N/veiK7n3Bq1iUwfNAR0NlCeEdG3/F2hEXaww8KEDuPIfcr301m+dwhoor5i6769NUzsbCmaO1kADuquSQ0/n3Zxr8FM/Qt9ieL+vB82XX0mWOYc6GZGUvqtZL0oHBClJ9fjyDVO5wCQ70k3d3vdquh6ovpXYj1teUHSFIwSKn01gTaaBTERN3P8ivmiEib8A0luTKVpkO/OnUnWO+i4vxyC/0w0BmPHkKafkW4mMaEvkTyMWOI0vqzf4TvTsrvHmgKYUBXrTosGbwMc0i1g7LmtsqGMy1CjDjZ+iIbDGCMy4si7E6Dz0e/wKTLhitfWPnFfuA1K2fZtyYqgcpUq95j3fipD3cpgwfDX6zCcLoa86HnbrHsrRKPo5ynEnjVEv0C92baoSd3oF+//5bL+zJoApGyfPnti9ZCXYu91jo6UGUuc3La6hH3WCqdb88p+rVFgC9cpZZxkmP8jYMbgLMEdR9xfLPc4o9L1MnemaKDwTYH9wC+nY8PsX3+reJzqn+duhH5gqW6tDTF1HB1CPm6RJ1RtGN4328g/Em8oXoHd0h9KsNYWIUv5JNOGSam6gwuzciLZSMk1g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
